name: Auto Convert and Archive

on:
  push:
    paths:
      - 'images/*.png' # 어떤 이름의 PNG가 올라와도 실행

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 파일 생성 및 이동 권한
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install Pillow
      - run: python convert.py
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update latest.webp and archive original" || exit 0
          git push
